const stock = [
    {
        id: 1,
        marca: 'Nike',
        modelo: 'Dunk Off-White Lot 1',
        precio: 100,
        img: "build/img/nikedunklot1.webp",
        talles: [37, 38, 39],
    },
    {
        id: 2,
        marca: 'Nike',
        modelo: 'Dunk Lilac',
        precio: 95,
        img: "build/img/nikedunklowlilac.webp",
        talles: [37, 38, 39],
    },
    {
        id: 3,
        marca: 'Adidas',
        modelo: 'Forum Bad Bunny Pink',
        precio: 100,
        img: "build/img/Adidas Forum Low Bad Bunny Pink.webp",
        talles: [42, 43, 44],
    },
    {
        id: 4,
        marca: 'Nike',
        modelo: 'SB Dunk Travis Scott',
        precio: 100,
        img: "build/img/Nike SB Dunk Travis Scott.webp",
        talles: [42, 43, 44],
    },
    {
        id: 5,
        marca: 'Nike',
        modelo: 'Jordan 1 Mid Barely Orange',
        precio: 100,
        img: "build/img/Nike Air Jordan 1 Mid Barely Orange.webp",
        talles: [42, 43, 44],
    },
    {
        id: 6,
        marca: 'Nike',
        modelo: 'Dunk Off-White Futura UNC',
        precio: 100,
        img: "build/img/Nike Dunk Low Off-White Futura UNC.webp",
        talles: [42, 43, 44],
    },
    {
        id: 7,
        marca: 'Nike',
        modelo: 'Jordan 1 High Off-White University Blue',
        precio: 100,
        img: "build/img/Nike Air Jordan 1 High Off-White University Blue.webp",
        talles: [42, 43, 44],
    },
    {
        id: 8,
        marca: 'Nike',
        modelo: 'Jordan 1 High Off-White',
        precio: 100,
        img: "build/img/Nike Air Jordan 1 High Off-White.webp",
        talles: [42, 43, 44],
    },
    {
        id: 9,
        marca: 'Adidas',
        modelo: 'Yezzy Boost 350 Zebra',
        precio: 100,
        img: "build/img/Adidas Yezzy Boost 350 V2 Zebra.webp",
        talles: [42, 43, 44],
    },
    {
        id: 10,
        marca: 'Adidas',
        modelo: 'Yezzy Boost 350 Oreo',
        precio: 100,
        img: "build/img/Adidas Yezzy Boost 350 V2 Oreo.webp",
        talles: [42, 43, 44],
    },
    {
        id: 11,
        marca: 'Nike',
        modelo: 'Uptempo Black White',
        precio: 100,
        img: "build/img/Nike Air Uptempo Black White.webp",
        talles: [44],
    },
    {
        id: 12,
        marca: 'Nike',
        modelo: 'Air Force 1 Double Air',
        precio: 95,
        img: "build/img/Nike Air Force 1 Low Double Air.webp",
        talles: [42, 43],
    },
];