const stock = [
    // Zapatillas
    {
        id: 1,
        tipo: 'zapatilla',
        marca: 'Nike',
        modelo: 'Dunk Off-White Lot 1',
        precio: 100,
        img: "build/img/nikedunklot1.webp",
        talles: [39, 40, 41],
    },
    {
        id: 2,
        tipo: 'zapatilla',
        marca: 'Nike',
        modelo: 'Dunk Lilac',
        precio: 95,
        img: "build/img/nikedunklowlilac.webp",
        talles: [42, 43, 44],
    },
    {
        id: 3,
        tipo: 'zapatilla',
        marca: 'Adidas',
        modelo: 'Forum Bad Bunny Pink',
        precio: 100,
        img: "build/img/Adidas Forum Low Bad Bunny Pink.webp",
        talles: [42, 43, 44],
    },
    {
        id: 4,
        tipo: 'zapatilla',
        marca: 'Nike',
        modelo: 'SB Dunk Travis Scott',
        precio: 100,
        img: "build/img/Nike SB Dunk Travis Scott.webp",
        talles: [42, 43, 44],
    },
    {
        id: 5,
        tipo: 'zapatilla',
        marca: 'Nike',
        modelo: 'Jordan 1 Mid Barely Orange',
        precio: 100,
        img: "build/img/Nike Air Jordan 1 Mid Barely Orange.webp",
        talles: [42, 43, 44],
    },
    {
        id: 6,
        tipo: 'zapatilla',
        marca: 'Nike',
        modelo: 'Dunk Off-White Futura UNC',
        precio: 100,
        img: "build/img/Nike Dunk Low Off-White Futura UNC.webp",
        talles: [42, 43, 44],
    },
    {
        id: 7,
        tipo: 'zapatilla',
        marca: 'Nike',
        modelo: 'Jordan 1 High Off-White University Blue',
        precio: 100,
        img: "build/img/Nike Air Jordan 1 High Off-White University Blue.webp",
        talles: [42, 43, 44],
    },
    {
        id: 8,
        tipo: 'zapatilla',
        marca: 'Nike',
        modelo: 'Jordan 1 High Off-White',
        precio: 100,
        img: "build/img/Nike Air Jordan 1 High Off-White.webp",
        talles: [42, 43, 44],
    },
    {
        id: 9,
        tipo: 'zapatilla',
        marca: 'Adidas',
        modelo: 'Yezzy Boost 350 Zebra',
        precio: 100,
        img: "build/img/Adidas Yezzy Boost 350 V2 Zebra.webp",
        talles: [42, 43, 44],
    },
    {
        id: 10,
        tipo: 'zapatilla',
        marca: 'Adidas',
        modelo: 'Yezzy Boost 350 Oreo',
        precio: 100,
        img: "build/img/Adidas Yezzy Boost 350 V2 Oreo.webp",
        talles: [42, 43, 44],
    },
    {
        id: 11,
        tipo: 'zapatilla',
        marca: 'Nike',
        modelo: 'Uptempo Black White',
        precio: 100,
        img: "build/img/Nike Air Uptempo Black White.webp",
        talles: [44],
    },
    {
        id: 12,
        tipo: 'zapatilla',
        marca: 'Nike',
        modelo: 'Air Force 1 Double Air',
        precio: 95,
        img: "build/img/Nike Air Force 1 Low Double Air.webp",
        talles: [42, 43],
    },

    // Buzos
    {
        id: 1,
        tipo: 'buzo',
        modelo: 'HOODIE GENETIC THEM - ORANGE',
        precio: 35,
        img: "build/img/1-ad.webp",
        talles: ["XL"],
    },
    {
        id: 2,
        tipo: 'buzo',
        modelo: 'HOODIE UNIVERSITY',
        precio: 30,
        img: "build/img/12-ad.webp",
        talles: ["M"],
    },
    {
        id: 3,
        tipo: 'buzo',
        modelo: 'HOODIE COALLITION WHITE',
        precio: 40,
        img: "build/img/3-ad.webp",
        talles: ["L"],
    },
    {
        id: 4,
        tipo: 'buzo',
        modelo: 'HOODIE COALLITION PINK',
        precio: 40,
        img: "build/img/4-ad.webp",
        talles: ["XL"],
    },
    {
        id: 5,
        tipo: 'buzo',
        modelo: 'HOODIE COALLITION PINK',
        precio: 40,
        img: "build/img/5-ad.webp",
        talles: ["XXL"],
    },

    // Remeras
    {
        id: 1,
        tipo: 'remera',
        modelo: 'T-SHIRT DELIGHTED - BROWN',
        precio: 16,
        img: "build/img/rem-1-ad.webp",
        talles: ["XL"],
    },
    {
        id: 2,
        tipo: 'remera',
        modelo: 'Paintings Black',
        precio: 12,
        img: "build/img/rem-4-ad.webp",
        talles: ["S"],
    },


];